# Generated by Django 5.1 on 2025-11-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
